
// COISAS PARA FAZER NO PROJETO:

// TODO IMPLEMENTAR SISTEMA DE NOTIFICAÇÕES DE SETORES

// TODO IMPLEMENTAR ALERTA DE ERRO OU SUCESSO NOS CADASTROS

// FIXME COLOCAR RECARREGAMENTO AUTOMÁTICO DA PÁGINA NA DASHBOARD AO ADICIONAR EVENTO

// FEITO COLOCAR NA ABA SUPORTE UM FORM PARA REPORTS DE ERROS E SUGESTÕES DOS USERS

// FEITO AO LOGAR DASHBOARD NÃO CARREGA DEVIDO A FUNÇÃO DE ALTERAR IMAGEM

// FEITO IMPLEMENTAR ALERTA DE USUÁRIO INVÁLIDO
