
// COISAS PARA FAZER NO PROJETO:

// TODO TENTAR FAZER REDIRECIONAMENTO PARA O EVENTO AO CLICAR NA NOTIFICAÇÃO(BOA SORTE GUERREIRO)

// IDEIA PARA EXECUTAR OQUE ESTÁ ACIMA: TENTAR PEGAR VALORES PARA SETAR UMA BUSCA (SIMULAR COMO SE O USUÁRIO TIVESSE CLICADO ATÉ CHEGAR NAQUELE EVENTO)

// GERAR UM HREF PRA CADA EVENTO

// TODO IMPLEMENTAR ALERTA DE ERRO OU SUCESSO NOS CADASTROS

// FIXME COLOCAR RECARREGAMENTO AUTOMÁTICO DA PÁGINA NA DASHBOARD AO ADICIONAR EVENTO

// FEITO IMPLEMENTAR SISTEMA DE NOTIFICAÇÕES DE SETORES - PRÓXIMA VERSÃO

// FEITO MARCAS NÃO ESTÕ APARECENDO NA CONSULTA DE FORNECEDOR, APENAS EQP

// FEITO CORRIGIR O PROBLEMA QUE OD DOIS FILTROS NÃO ESTÃO FUNCIONANDO JUNTOS - PELO VISTO CORRIGIDO

// FEITO CORREÇÃO DE RELAÇÃO ENTRE TABELAS DOS EQUIPAMENTOS

// FEITO COLOCAR NA ABA SUPORTE UM FORM PARA REPORTS DE ERROS E SUGESTÕES DOS USERS

// FEITO AO LOGAR DASHBOARD NÃO CARREGA DEVIDO A FUNÇÃO DE ALTERAR IMAGEM

// FEITO IMPLEMENTAR ALERTA DE USUÁRIO INVÁLIDO

// TODO FIM DE SEMANA DEVE TER SIDO DOIDERA NÉ MEU BOM??? ENTÃO BORA CORRER ATRÁS ESSA SEMANA POR QUE O SISTEMA NÃO SE FAZ SOZINHO!!!

// FIXME VOCÊ É UMA PESSOA FODA MEU CAMARADA, TENHA FORÇA E NUNCA DESISTA, LEMBRE QUE SUA VÓ FICARIA ORGULHOSA DE VOCÊ, A VIDA É SOPRO, NÃO É? VOA PEDRINHO!!!
