
// COISAS PARA FAZER NO PROJETO:

// TODO IMPLEMENTAR SISTEMA DE NOTIFICAÇÕES DE SETORES - PRÓXIMA VERSÃO

// TODO IMPLEMENTAR ALERTA DE ERRO OU SUCESSO NOS CADASTROS

// FIXME COLOCAR RECARREGAMENTO AUTOMÁTICO DA PÁGINA NA DASHBOARD AO ADICIONAR EVENTO

// FIXME CORRIGIR O PROBLEMA QUE OD DOIS FILTROS NÃO ESTÃO FUNCIONANDO JUNTOS - PELO VISTO CORRIGIDO

// FIXME MARCAS NÃO ESTÕ APARECENDO NA CONSULTA DE FORNECEDOR, APENAS EQP

// FEITO CORREÇÃO DE RELAÇÃO ENTRE TABELAS DOS EQUIPAMENTOS

// FEITO COLOCAR NA ABA SUPORTE UM FORM PARA REPORTS DE ERROS E SUGESTÕES DOS USERS

// FEITO AO LOGAR DASHBOARD NÃO CARREGA DEVIDO A FUNÇÃO DE ALTERAR IMAGEM

// FEITO IMPLEMENTAR ALERTA DE USUÁRIO INVÁLIDO
